import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import PromotionalBanner from "./components/PromotionalBanner";
import NavigationBar from "./components/NavigationBar";
import Footer from "./components/Footer";

import { CartProvider } from "./context/CartContext";
import { WishlistProvider } from "./context/WishListContext";
import { AuthProvider } from"../src/context/AuthContext"; // ✅ import AuthProvider
import { AdminProvider } from "../src/context/AdminContext"; // ✅ import AdminProvider
import { ToastProvider } from "./context/ToastContext";
import { CouponProvider } from "./context/CouponContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Exclusive E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ ToastProvider should wrap everything so that toast context is available globally */}
        <ToastProvider>
          <AuthProvider>
            <AdminProvider>
              <WishlistProvider>
                <CartProvider>
                  <CouponProvider>
                    <PromotionalBanner />
                    <NavigationBar />
                    <div className="min-h-screen">{children}</div>
                    <Footer />
                    <Toaster />
                  </CouponProvider>
                </CartProvider>
              </WishlistProvider>
            </AdminProvider>
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
