import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import PromotionalBanner from "./components/PromotionalBanner";
import NavigationBar from "./components/NavigationBar";
import Footer from "./components/Footer";
import { CartProvider } from "./context/CartContext"; // ✅ Import the cart context provider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Make CartProvider wrap everything so cart state is global */}
        <CartProvider>
          <PromotionalBanner />
          <NavigationBar />
          <div className="min-h-screen">
            {children}
          </div>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
