import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import PromotionalBanner from "./components/PromotionalBanner";
import NavigationBar from "./components/NavigationBar";
import Footer from "./components/Footer";

import { CartProvider } from "./context/CartContext";
import { WishlistProvider } from "./context/WishListContext"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Exclusive E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Wrap with WishlistProvider → then CartProvider */}
        <WishlistProvider>
          <CartProvider>
            <PromotionalBanner />
            <NavigationBar />
            <div className="min-h-screen">
              {children}
            </div>
            <Footer />
          </CartProvider>
        </WishlistProvider>
      </body>
    </html>
  );
}
